spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test-kakao-client-id
          google:
            client-id: test-google-client-id
            client-secret: test-google-client-secret
          naver:
            client-id: test-naver-client-id
            client-secret: test-naver-client-secret

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  ai:
    openai:
      api-key: test-openai-api-key

custom:
  jwt:
    secretKey: 'dGVzdC1zZWNyZXQta2V5LWZvci1pbnRlZ3JhdGlvbi10ZXN0cy1tdXN0LWJlLWxvbmdlci10aGFuLTI1Ni1iaXRz'
  frontend:
    url: http://localhost:8081